### ISSUE TITLE
Add Sapiens font to the H tags using CSS 

### ISSUE THREAD

**Issue by SirLich** [Sapiens-OSS/sapiens-modding-wiki#17]
Edit: Turns out this is trickier than I thought.

**Comment by DecDuck** [comment]
Is this what you wanted?
![Screenshot from 2022-09-19 23-28-52](https://user-images.githubusercontent.com/64579723/191136639-ea8c2e73-d790-46bd-a1fa-5d280f1718b0.png)

**Comment by DecDuck** [comment]
[Pull request](https://github.com/Sapiens-OSS/sapiens-modding-wiki/pull/24)

**Comment by DecDuck** [comment]
Still need to work out specifics on when to apply the style, but it will be part of my next PR

**Comment by DecDuck** [comment]
#26
