### ISSUE TITLE
[Hammerstone] Documentation on the key-binding stuff is incorrect

### ISSUE THREAD

**Issue by SirLich** [Sapiens-OSS/sapiens-modding-wiki#25]
It's like 'mostly' correct, but wrong in a lot of places. See this mod for how it's actually used: https://github.com/SirLich/sapiens-abandon-tribe

**Comment by DecDuck** [comment]
The secondary key vs modifier will be fixed with my next PR. Are there any other problems with it?

**Comment by DecDuck** [comment]
#26
