### ISSUE TITLE
Shader compilation fails when path contains space

### ISSUE THREAD

**Issue by Oman395** [Sapiens-OSS/sapiens-modding-wiki#41]
Hey there, I was trying to compile a shader using the Sapiens Shader Compiler script, but my username on windows had a space in it-- this caused glslc to throw a fit, because the paths were split into two arguments. I tried editing the script to prepend a backslash to spaces, but I forgot that windows uses backslashes instead of normal slashes for folder paths. I then tried encasing it in quotes (single and double), to which glslc complained the path was incorrectly formatted. The only way I fixed it was by copying the mod folder, moving it somewhere without a space in the path, than copying it back. A note for this should be added to the docs, because I don't think it's possible to fix this without glslc doing something.

**Comment by SirLich** [comment]
Hi! Thanks for letting me know. 

The 'Shader Compiler Script' isn't anything special -it's just something I threw together to help me. I guess I wasn't particularly careful with the programming.

It should be an easy fix, but I'm not sure when I would have time to update the gist. 

If you want, you can also join the discord: https://discord.gg/WnN8hj2Fyg

**Comment by Oman395** [comment]
Nah, it's not your script-- it's glslc. Literally can't even handle paths in quotes, and windows means that we can't even escape the space. I think the only thing that can be done is to edit the gist to say something like "Note - if the path to your folder contains spaces, the script will have errors, as a result of issues beyond our control. The only way we've found to fix it is to copy your folder over to a path that doesn't contain spaces, run it the script, and copy it back."
